#!/bin/bash

# 确保接收至少两个参数
if [ $# -lt 2 ]; then
    echo "Usage: $0 <ph_files>... <fasta_files>..."
    exit 1
fi

# 处理所有传递的文件
for file in "$@"; do
    if [[ -f $file && $file == cluster*.aln_nn.ph ]]; then
        new_file="${file%.aln_nn.ph}.ph"
        mv "$file" "$new_file"
        cp "$new_file" .
        echo "Renamed $file to $new_file"
    elif [[ -f $file && $file == cluster*.fasta_aln_aa ]]; then
        new_file="${file%.fasta_aln_aa}.fasta"
        mv "$file" "$new_file"
        cp "$new_file" .
        echo "Renamed $file to $new_file"
    fi
done