#!/bin/bash

# Function to check clusters with only one member and handle them accordingly
function checkGroupOneMember {
    local num_candidates=3
    echo " [RUN] Checking clusters with only one member"

    local seqs=$(awk '$6 == 1 {print $7}' "$CLUSTER_FILE" | tr ',' ' ')

    for seq in $seqs; do
        echo "    [WARNING] Cluster with one sequence: $seq"
        local candidates=$(grep "$seq" "$SIMILARITY_FILE" | sort -g -k3 -r | awk -v s="$seq" \
            '$1 != s {print $1} $2 != s {print $2}' | head -n $num_candidates)

        for candidate in $candidates; do
            local check_num=$(awk -v can="$candidate" '$0 ~ can {print $6}' "$CLUSTER_FILE")
            if [ -n "$check_num" ] && (( check_num >= 1 )); then
                echo "    Adding to group of: $candidate"
                local list=$(awk -v can="$candidate" '$0 ~ can {print $7}' "$CLUSTER_FILE")
                local new_num=$((check_num + 1))
                sed -i "/$seq/d" "$CLUSTER_FILE"
                perl -pi -e "s/$check_num\t$list/$new_num\t$list$seq,/" "$CLUSTER_FILE"
                break
            fi
        done
    done
}

# Set variables
SEQ_TMP=$2
CLUSTER_FILE="cluster.txt"
CLUSTER_VS_SPECIES_TABLE="clusterTable.csv"
SIMILARITY_FILE=$1

HCLUSTER_CMD="hcluster_sg"
BLAST_CMD="blastpgp"
FORMATDB_CMD="formatdb"
CLUSTER2TABLE_CMD="summary_cluster.pl"
SPLIT_CMD="splitFasta2singleSeq.pl"

BLAST_THE="1e-3"
MIN_EDGE_WEIGHT=20

# Cluster sequences by HCluster
echo " [RUN] HCluster"
SPECIES_NUM=$3
echo "$SPECIES_NUM sequences"
echo "Similarity file: $SIMILARITY_FILE"
$HCLUSTER_CMD -w $MIN_EDGE_WEIGHT -m $SPECIES_NUM -o $CLUSTER_FILE "$SIMILARITY_FILE"

if [ -e "$CLUSTER_FILE" ]; then
    checkGroupOneMember
    echo "  [INFO] Number of clusters: $(wc -l < "$CLUSTER_FILE")"
else
    echo "  [ERROR] No $CLUSTER_FILE, failed in HCluster"
    exit 1
fi

# Create group vs species table for analysis
$CLUSTER2TABLE_CMD "$CLUSTER_FILE" > "$CLUSTER_VS_SPECIES_TABLE"

# Identify sequences not included in any cluster
echo "Identifying sequences not included in any cluster..."

# Set variables
SEQ_TMP=$2  # This is your full sequence dataset
UNCLUSTERED_SEQS="unclustered_seqs.txt"


# 提取已分群的序列ID
awk -F'\t' '{gsub(/\r|\n/, "", $7); split($7, a, ","); for (i in a) print a[i]}' "$CLUSTER_FILE" > clustered_seq_ids.txt

echo "Clustered Sequence IDs:"
cat clustered_seq_ids.txt

# 从原始序列文件中删除已分类的序列
awk 'BEGIN{while((getline < "clustered_seq_ids.txt") > 0) clustered[$1] = 1} /^>/ {p = !(substr($1, 2) in clustered)} p' "$SEQ_TMP" > unclustered_seqs.fasta

echo "Unclustered Sequences saved to unclustered_seqs.fasta:"
cat unclustered_seqs.fasta

